export interface CarePointDef {
  code: string;
  orderIdx: number;
  title: string;
  content: string;
  mustFlag: boolean;
  keywords: string[];
  evidenceHints: string[];
}

export interface CarePointVersionDef {
  version: string;
  title: string;
  summary: string;
  isActive: boolean;
  points: CarePointDef[];
}

export const POINT_VERSIONS: CarePointVersionDef[] = [
  {
    version: 'v1.0',
    title: '肠造口居家自护要点 v1.0',
    summary: '基础六项通用要点，已停止使用，仅作为历史版本对比。',
    isActive: false,
    points: [
      {
        code: 'P1',
        orderIdx: 1,
        title: '洗手与准备',
        content: '操作前规范洗手，准备造口袋、温水、毛巾与垃圾袋。',
        mustFlag: true,
        keywords: ['洗手', '准备', '造口袋', '温水', '毛巾'],
        evidenceHints: ['洗手', '准备了', '温水', '毛巾', '垃圾袋'],
      },
      {
        code: 'P2',
        orderIdx: 2,
        title: '造口周围皮肤清洁',
        content: '使用温水轻柔清洁造口及周围皮肤。',
        mustFlag: true,
        keywords: ['清洁', '温水', '皮肤'],
        evidenceHints: ['温水', '擦洗', '清洁', '皮肤'],
      },
      {
        code: 'P3',
        orderIdx: 3,
        title: '造口大小测量',
        content: '测量造口大小并记录。',
        mustFlag: true,
        keywords: ['测量', '造口', '大小', '记录'],
        evidenceHints: ['测量', '记录', '大小', '尺寸'],
      },
      {
        code: 'P4',
        orderIdx: 4,
        title: '底盘更换',
        content: '轻柔揭除旧底盘，按标准粘贴新底盘并按压 1 分钟。',
        mustFlag: true,
        keywords: ['底盘', '更换', '粘贴', '按压'],
        evidenceHints: ['底盘', '粘贴', '按压', '换底盘'],
      },
      {
        code: 'P5',
        orderIdx: 5,
        title: '排泄物观察',
        content: '记录造口排泄物颜色、性状与时间。',
        mustFlag: true,
        keywords: ['排泄物', '颜色', '性状', '记录'],
        evidenceHints: ['颜色', '性状', '量', '时间'],
      },
      {
        code: 'P6',
        orderIdx: 6,
        title: '皮肤观察',
        content: '观察造口及周围皮肤是否异常。',
        mustFlag: true,
        keywords: ['皮肤', '异常', '观察'],
        evidenceHints: ['红肿', '破溃', '过敏', '瘙痒', '渗漏'],
      },
    ],
  },
  {
    version: 'v2.0',
    title: '肠造口居家自护要点 v2.0',
    summary: '当前激活版本，由造口专科护士审核后启用，共 8 项要点。',
    isActive: true,
    points: [
      {
        code: 'P1',
        orderIdx: 1,
        title: '准备与洗手',
        content:
          '备齐造口袋、皮肤保护剂、温水、软毛巾与垃圾袋，操作前使用流动水规范洗手。',
        mustFlag: true,
        keywords: ['准备', '洗手', '造口袋', '温水', '垃圾袋', '保护剂'],
        evidenceHints: [
          '准备好了',
          '洗手',
          '流动水',
          '七步洗手法',
          '温水',
          '造口袋',
          '皮肤保护剂',
          '软毛巾',
          '垃圾袋',
        ],
      },
      {
        code: 'P2',
        orderIdx: 2,
        title: '造口周围皮肤清洁',
        content:
          '使用温水轻拭造口及周围皮肤，避免酒精、碘伏等刺激性消毒剂。',
        mustFlag: true,
        keywords: ['清洁', '温水', '皮肤', '造口', '消毒剂'],
        evidenceHints: [
          '温水',
          '擦',
          '洗',
          '没有用酒精',
          '没用碘伏',
          '周围皮肤',
          '清洁',
          '擦干',
        ],
      },
      {
        code: 'P3',
        orderIdx: 3,
        title: '造口与底盘尺寸评估',
        content: '观察造口颜色与形态，测量造口大小并记录。',
        mustFlag: true,
        keywords: ['测量', '造口', '大小', '颜色', '形态', '记录'],
        evidenceHints: [
          '测了',
          '测量',
          '记录',
          '颜色',
          '粉红',
          '红润',
          '大小',
          '尺寸',
          '形态',
        ],
      },
      {
        code: 'P4',
        orderIdx: 4,
        title: '旧底盘移除与底盘更换',
        content:
          '轻柔揭除旧底盘，必要时使用底盘剥离喷剂，按标准粘贴新底盘并按压 1–2 分钟。',
        mustFlag: true,
        keywords: ['底盘', '揭除', '粘贴', '按压', '剥离'],
        evidenceHints: [
          '轻轻揭',
          '揭掉',
          '撕下来',
          '粘贴',
          '贴上',
          '按压',
          '压了',
          '底盘',
          '底板',
          '剥离喷剂',
        ],
      },
      {
        code: 'P5',
        orderIdx: 5,
        title: '排泄物观察',
        content: '记录造口排泄物的颜色、性状、量与时间。',
        mustFlag: true,
        keywords: ['排泄物', '颜色', '性状', '量', '时间', '造口'],
        evidenceHints: [
          '颜色',
          '性状',
          '量',
          '时间',
          '排出',
          '记录',
          '稀',
          '糊状',
          '成形',
          '粘液',
        ],
      },
      {
        code: 'P6',
        orderIdx: 6,
        title: '皮肤与并发症观察',
        content: '观察造口及周围皮肤是否出现红肿、破溃、过敏、异味、渗漏。',
        mustFlag: true,
        keywords: ['皮肤', '红肿', '破溃', '过敏', '异味', '渗漏'],
        evidenceHints: [
          '皮肤',
          '红',
          '肿',
          '破',
          '破溃',
          '过敏',
          '痒',
          '异味',
          '味道',
          '渗漏',
          '漏',
          '发红',
        ],
      },
      {
        code: 'P7',
        orderIdx: 7,
        title: '用物与废弃物处理',
        content: '将使用过的底盘、造口袋按生活垃圾分类投放，妥善保存备用物品。',
        mustFlag: false,
        keywords: ['废弃物', '垃圾', '分类', '备用', '保存'],
        evidenceHints: [
          '垃圾袋',
          '垃圾分类',
          '生活垃圾',
          '收好',
          '保存',
          '备用',
          '处理',
        ],
      },
      {
        code: 'P8',
        orderIdx: 8,
        title: '求助与随访安排',
        content:
          '发现异常或不确定时记录要点并提交，等待造口专科护士在随访前联系。',
        mustFlag: true,
        keywords: ['求助', '异常', '随访', '记录', '提交'],
        evidenceHints: [
          '求助',
          '担心',
          '不放心',
          '异常',
          '不确定',
          '随访',
          '联系',
          '记录',
          '提交',
        ],
      },
    ],
  },
  {
    version: 'v3.0-草稿',
    title: '肠造口居家自护要点 v3.0（草稿）',
    summary: '在 v2.0 基础上新增心理支持与社交场景维度，尚未启用。',
    isActive: false,
    points: [
      {
        code: 'P1',
        orderIdx: 1,
        title: '准备与洗手',
        content: '同 v2.0 第 1 项。',
        mustFlag: true,
        keywords: ['准备', '洗手'],
        evidenceHints: ['洗手', '准备', '造口袋'],
      },
      {
        code: 'P2',
        orderIdx: 2,
        title: '造口周围皮肤清洁',
        content: '同 v2.0 第 2 项。',
        mustFlag: true,
        keywords: ['清洁', '温水', '皮肤'],
        evidenceHints: ['温水', '清洁', '皮肤'],
      },
      {
        code: 'P3',
        orderIdx: 3,
        title: '造口与底盘尺寸评估',
        content: '同 v2.0 第 3 项。',
        mustFlag: true,
        keywords: ['测量', '造口', '大小'],
        evidenceHints: ['测量', '记录', '大小'],
      },
      {
        code: 'P4',
        orderIdx: 4,
        title: '旧底盘移除与底盘更换',
        content: '同 v2.0 第 4 项。',
        mustFlag: true,
        keywords: ['底盘', '粘贴', '按压'],
        evidenceHints: ['底盘', '粘贴', '按压'],
      },
      {
        code: 'P5',
        orderIdx: 5,
        title: '排泄物观察',
        content: '同 v2.0 第 5 项。',
        mustFlag: true,
        keywords: ['排泄物', '颜色', '性状'],
        evidenceHints: ['颜色', '性状', '量'],
      },
      {
        code: 'P6',
        orderIdx: 6,
        title: '皮肤与并发症观察',
        content: '同 v2.0 第 6 项。',
        mustFlag: true,
        keywords: ['皮肤', '红肿', '渗漏'],
        evidenceHints: ['红', '肿', '渗漏'],
      },
      {
        code: 'P7',
        orderIdx: 7,
        title: '用物与废弃物处理',
        content: '同 v2.0 第 7 项。',
        mustFlag: false,
        keywords: ['废弃物', '垃圾'],
        evidenceHints: ['垃圾袋', '分类'],
      },
      {
        code: 'P8',
        orderIdx: 8,
        title: '求助与随访安排',
        content: '同 v2.0 第 8 项。',
        mustFlag: true,
        keywords: ['求助', '随访'],
        evidenceHints: ['求助', '随访'],
      },
      {
        code: 'P9',
        orderIdx: 9,
        title: '心理与社交支持（草稿）',
        content: '记录近一周的社交与情绪变化，是否出现回避聚会、情绪低落等情况。',
        mustFlag: false,
        keywords: ['心理', '情绪', '社交', '聚会', '回避'],
        evidenceHints: ['情绪', '低落', '聚会', '回避', '焦虑', '压力'],
      },
    ],
  },
];
